quarkus.http.port=${PORT:8081}
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=2585
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.log.level=INFO
quarkus.hibernate-orm.log.format-sql=true
quarkus.hibernate-orm.log.bind-parameters=true

#HIBERNATE STATISTICS
quarkus.hibernate-orm.statistics=true

#DATASOURCE METRICS
quarkus.datasource.metrics.enabled=true

# POSTGRES SLOW QUERY LOGGING
log_min_duration_statement=50

