quarkus.http.port=8080
quarkus.http.host=0.0.0.0
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=nibro
quarkus.datasource.password=L1aPn9YlkJbmEaFEv814Om2Z3MGxfgSM
quarkus.datasource.jdbc.url=jdbc:postgresql://dpg-d8s5pefavr4c73fbps10-a.oregon-postgres.render.com:5432/eventhub_3up3?sslmode=require
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.log.level=INFO
quarkus.hibernate-orm.log.format-sql=true
quarkus.hibernate-orm.log.bind-parameters=true
quarkus.datasource.jdbc.additional-jdbc-properties.sslmode=require
#HIBERNATE STATISTICS
quarkus.hibernate-orm.statistics=true

#DATASOURCE METRICS
quarkus.datasource.metrics.enabled=true

# POSTGRES SLOW QUERY LOGGING
log_min_duration_statement=50

quarkus.datasource.devservices.enabled=false
quarkus.datasource.reactive=false